project_id = "orbit"

[db]
port = 54322
major_version = 15

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "25MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
# Desactive en developpement pour ne pas dependre d'un service de mail.
enable_confirmations = false
